### ISSUE TITLE
State Graphs

### ISSUE THREAD

**Issue by mtaffe01** [mtaffe01/WIDS2024FinalProject#6]
For facets, use best judgement if by state, decade, year, or region.
* maybe make all states light grey and just choose outline outlier states and maybe regional averages.
2. Party by state and year
3. Min Wage by state and year (include fed (facet or use by decades where necessary)
4. Adjusted Min Wage by state and year (include adjusted fed (facet or use by decades where necessary)
5. Union employment, CB employment, and full employment (facet by decade)
6. percent union and percent collective bargaining

**Comment by melaniejklein** [comment]
graph 3 and 4
figure out spacing of graph
can't do a line for federal minimum wage unless faceted by year instead of decade
add a label for the line saying federal minimum wage

**Comment by melaniejklein** [comment]
graph 5
should we take the average value per decade?
# add a key for the color of the points
fix spacing because union employment count is not visible

**Comment by mtaffe01** [comment]
we did this
